### PR TITLE
Editor for Bestiary field of GAM file for PST

### PR DESCRIPTION
**Pull request by Mingun**
This PR is based on #9. Some screenshots:

Before:
bestiary_before

After:
bestiary_after1
bestiary_after2

Bestiary can be edited or in table view (for known bytes), or in HEX view (for all bytes, unused bytes highlighted). Also editor shows description and image of the creature.

### CODE REVIEW

**Comment by Mingun** [comment]
I also have noticed that JHexView API quite strongly differs from an [upstream](https://github.com/sporst/JHexView). Didn't you think to make honest fork and to depend on it instead of holding sources as zip archive in this repository?

**Comment by Argent77** [comment]
I have reviewed this PR more thoroughly. Very impressive. A couple of points though:
- As hinted in PR #9, removing horizontal restraints from all advanced field controls just to make the Bestiary control working correctly is not acceptable. I'll stall merging this PR for the time being. Maybe setting a minimum size, possibly in combination with a scroll pane, could yield a more favorable result for this control?
- The `Creature[]` array is currently filled statically. To account for modded games I would suggest to retrieve the required data from `beast.ini` instead. The file can always be found in the root directory of the game. You can use the `IniXXX` classes from the `org.infinity.util` package to save some work. The static data can still be useful in case the game installation doesn't provide a `beast.ini` file.

> I also have noticed that JHexView API quite strongly differs from an upstream. Didn't you think to make honest fork and to depend on it instead of holding sources as zip archive in this repository?

I agree, it's worth a thought to turn it into a more legitimate solution.

**Comment by Mingun** [comment]
> The Creature[] array is currently filled statically. To account for modded games I would suggest to retrieve the required data from `beast.ini` instead

Wow! I did not even know about it. Damn! I spent several hours for filling of the `Creature[]` array...

>  Maybe setting a minimum size, possibly in combination with a scroll pane, could yield a more favorable result for this control?

Ok, I will look what can be made. The reason for which I wanted to expand the editor that some editors, like the editor of `Bitmap` and to it similar, sometimes have a horizontal scrollbar in the lists when on each side it is full of the place

**Comment by Mingun** [comment]
I found that `beast.ini` not shown in the resource tree. Before I begin to dig how to place it there, can you will give me some hints about it?

**Comment by Argent77** [comment]
> I found that `beast.ini` not shown in the resource tree. Before I begin to dig how to place it there, can you will give me some hints about it?

That's intended. Files in the game root folder (such as `baldur/icewind/torment.ini` or `var.var`) are not considered by the resource tree. They are accessible from the `Edit` menu though. It might be a good idea to add `beast.ini` as well.

**Comment by Mingun** [comment]
I almost completely changed implementation. Instead of use of hardcoded data now everything is read from the `beast.ini` file. As the game (at least the original version) does not show nothing in a bestiary if to delete it, then I did not do fallback.

I also made some improvements in comparison with the previous version:
- Other background color for party members (in the table and the HEX editor)
- Show `kill variable`s and the number of kills and also opportunity to open the `kill variable` editor by doubleclick on a row is added
- Not yet opened creatures in the bestiary in the table and HEX editor are shown gray
- Correct editor layout, now right after opening the sizes are correctly accented

bestiary

----

> They are accessible from the `Edit` menu though. It might be a good idea to add `beast.ini` as well.

You mean add this file to this menu too or add it to resource tree? On my opinion the last will be preferable, because there are many such files (`quests.ini`, `beast.ini` -- both a needed to fix #98) that stores in the game root and I think we can introduce new category -- `Game` -- for it

**Comment by Argent77** [comment]
Latest revision of the Bestiary Editor looks great. I think I can live with the current implementation of the UI components layout (resize dynamically to fit all content).

One small issue: The option to open kill variable by double-click is somewhat unintuitive. I would suggest to add a second method: right-click > context menu > `Open kill variable` (grayed out if selected entry doesn't provide kill variable).

> > They are accessible from the `Edit` menu though. It might be a good idea to add `beast.ini` as well.
> 
> You mean add this file to this menu too or add it to resource tree? On my opinion the last will be preferable, because there are many such files (`quests.ini`, `beast.ini` -- both a needed to fix [NearInfinityBrowser#98](https://github.com/NearInfinityBrowser/NearInfinity/issues/98)) that stores in the game root and I think we can introduce new category -- `Game` -- for it. Anyway, these changes if are not too busy at me, I will make in separate PR

I have researched a bit. It looks like these files can be accessed from non-standard locations:
- `Baldur.ini` / `Icewind.ini` / `Icewind2.ini` / `Torment.ini`: game root in classic BG(2)/IWD/IWD2/PST
- `Baldur.ini` / `Baldur.lua`: home root in all Enhanced Edition games, pre-2.0 / post-2.0
- `Party.ini`: game root in IWD2
- `BEAST.INI`: game root in PST
- `QUESTS.INI`: game root in PST
- `VAR.VAR`: game root in PST
- `WeiDU.log`: tracks installed mods, game root in all supported games

Some of them are currently accessible from the `Edit` menu. Depending on the game, the menu will be populated with up to 5 entries. All of them would still be manageable from the `Edit` menu. However, it might be easier to apply advanced search options (such as [NearInfinityBrowser#98](https://github.com/NearInfinityBrowser/NearInfinity/issues/98)) to collect them in a separate resource tree node. I would accept either solution, as separate PR.

**Comment by Mingun** [comment]
> Latest revision of the Bestiary Editor looks great. I think I can live with the current implementation of the UI components layout (resize dynamically to fit all content).

Just for you know, I revert changes that stretch other editors, only bestiary editor is stretched, because it require a lot of space.

----
I add context menu with some nice features. just see the screenshots:
context menu - table
context menu - raw

**Comment by Argent77** [comment]
I would suggest to move the 'beast.ini' entry to the global `Edit` menu for consistency (disable for all games except PST).

I'm also wondering whether a second `Raw` tab is really needed inside the Bestiary control. There is already the `Raw` tab of the parent resource, which provides access to the same range of data. Moreover you can convert the structure into hex mode via context menu if you need to.

**Comment by Mingun** [comment]
Ok, I remove hex tab. For moving `beast.ini` I create separate PR #22 and I still and I suggest to leave access to `beast.ini` from a context menu of a bestiary, just for convenience

**Comment by Mingun** [comment]
ping

**Comment by Mingun** [comment]
@Argent77, any news?

**Comment by Argent77** [comment]
Sorry for the long period of absence. I'll take care of the pending PRs shortly.

**Comment by Mingun** [comment]
Well, it's me again. Have you time to review?

**Comment by Argent77** [comment]
Everything looks great so far. Merged.

Thank you! And sorry for the long delay. Too many things came up in the meantime that kept me from working on NI.

(Btw, kudos for cleaning up BrowserMenuBar.java a bit.)

**Pull request merged**
