### PR TITLE
Improvements in dialog editor

### PR DESCRIPTION
**Pull request by Mingun**
This PR is a superset of #13. Improvements includes:
* NWN like tree: new option (default on) that disables infinity tree creation, especially for tree with cycles: nwn-like
* Ability to jump from **View** or **Edit** (via context menu on State/Response field) tab to tree node in tree viewer:
select in tree
* New option (default off): Ability to draw PC replies in another color, like in a NWN dialog editor
* New option (default on): Ability to hide technical information (state/response number) from the tree: complex

### CODE REVIEW

**Comment by Mingun** [comment]
@Argent77, can you review this?

**Comment by Argent77** [comment]
Impressive work. Resolving infinite dialog tree cycles was on my todo list for a long time. I don't know how useful an option for hiding state/response numbers may be, but it doesn't hurt to have the option.

I have found one issue though. Jumping from View tab to Tree View via new "Select in tree" quick button sometimes results in a NPE (example: DMORTE.DLG in PST). Can you look into it?

Full debug output:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at org.infinity.resource.dlg.StateItem.iterator(StateItem.java:97)
        at org.infinity.resource.dlg.DlgTreeModel.checkState(DlgTreeModel.java:253)
        at org.infinity.resource.dlg.DlgTreeModel.slowFindState(DlgTreeModel.java:282)
        at org.infinity.resource.dlg.DlgTreeModel.map(DlgTreeModel.java:241)
        at org.infinity.resource.dlg.TreeViewer.select(TreeViewer.java:244)
        at org.infinity.resource.dlg.DlgResource.selectInTree(DlgResource.java:360)
        at org.infinity.resource.dlg.Viewer$DlgPanel.actionPerformed(Viewer.java:692)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
        at java.awt.Component.processMouseEvent(Component.java:6539)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6304)
        at java.awt.Container.processEvent(Container.java:2239)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
        at java.awt.Container.dispatchEventImpl(Container.java:2283)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
        at java.awt.EventQueue$4.run(EventQueue.java:733)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by Mingun** [comment]
I fix this problem: it appears, when state/response is unattainable from a tree since it, most likely, or is achievable only from other dialog, or from a script. Now I just show the message about it, but further, I think, it will be possible to organize search of dialog through which such entries can be shown, or to insert such node into a tree as an additional root.

Also I fix expand/collapse commands: in some cases it throws NPEs and try to expand infinity trees. Now expanding stops at non-main nodes.

Also I noted that `(No text)` responses not correctly shows in tree: without response number. I fix this too.

As I prefer to have linear history, I made rebase. The only changed commit (in which there was a trivial conflict) -- aea7815548aeffecdedbadc10e5f7bb88644f902. Other commits remained the same.

Also I already have work on synchronization of tree structure with changes in states/responses. But I think, I suppose them in a separate PR. An ultimate goal -- an opportunity to edit dialog from tree

**Comment by Argent77** [comment]
Merged. Thank you.

**Pull request merged**
