### PR TITLE
Improve dialog editor: colorize entries from other dialogs

### PR DESCRIPTION
**Pull request by Mingun**
See screenshot:

colorized-dialog

### CODE REVIEW

**Comment by Mingun** [comment]
@Argent77, may be you think that option for such coloring is needed?

**Comment by Argent77** [comment]
> @Argent77, may be you think that option for such coloring is needed?

I think it helps readability of dialogs with multiple participants, but not everyone might want to use this feature. Can you add an option to turn it off?

**Comment by Mingun** [comment]
Done. I extract the menu in the class as I plan to add some more options in the future, and it simplifies maintainability

**Comment by Mingun** [comment]
@Argent77, can you look (and may be also other PRs)?

**Comment by Argent77** [comment]
> @Argent77, can you look (and may be also other PRs)?

I will look at this and the other PRs when I'm back home (probably mid or end of next week).

**Comment by Argent77** [comment]
Merged. Thank you.

**Pull request merged**
