### PR TITLE
Stretch complex field editor horizontally

### PR DESCRIPTION
**Pull request by Mingun**
Before:
before

After:
after

### CODE REVIEW

**Comment by Argent77** [comment]
Horizontal size limit has been deliberately set to a fixed amount, since fully stretched controls will be difficult to handle, especially on hi-res widescreen resolutions or high-dpi monitors.

**Comment by Mingun** [comment]
With this limit the bestiary editor collapses in a narrow strip:

without-stretch

Besides, I think that too big size can always be reduced, having just reduced a window, and too small so it is impossible to increase. If you agree, I updated the PR for a bestiary (resolve merge conflicts) including these changes

**Comment by Mingun** [comment]
Ok, as I made this PR in order that this improvement was merged, so far I work on a bestiary and as it will not be merged, I close it. I will continue work on the solution of this problem as part of #11.

**Comment by Mingun** [comment]
Just for note: without this change very unpleasant collapse of editors with the advent of horizontal scrolling when the place should be enough still is observed. Example: here I reduced width of a window of all by couple of pixels, and the editor collapsed:
filled
notfilled

**Pull request closed without merging**
