### PR TITLE
[WIP] Implement setting for show icons for items/spells in the stores/resource ref lists

### PR DESCRIPTION
**Pull request by Mingun**
Actually it had to be the first PR as initially I began work on it, but many places by which I could not pass in passing were found…:
pst - icons
pst - settings

### CODE REVIEW

**Comment by Argent77** [comment]
I find this feature useful in principle. However, performance is currently too slow to be usable. I have attached two VisualVM Profiler snapshots with more details.

**First call:**
icons-1
Snapshot file: [icons-1.xml.zip](https://github.com/Argent77/NearInfinity/files/2949246/icons-1.zip)

**Subsequent calls:**
icons-2
Snapshot file: [icons-2.xml.zip](https://github.com/Argent77/NearInfinity/files/2949247/icons-2.zip)

**Comment by Mingun** [comment]
Yes, performance is the reason for which I hide this feature behind the setting. Actually, from my point of view, such thin UI control is not required and icons could be shown always, but when `JList` is displayed at me such impression that all icons, even those that are not visible are drawn. While I had no time to deal with it and I decided that existence of the not very well optimized optional feature is better, than its absence.

I plan to look at performance concerns later if it in general is possible. I have some negative experience with Swing which is that occasionally absolutely inexplicable glitches emerge there which it is absolutely not clear how to bypass

**Comment by Mingun** [comment]
I made some researches -- when showing `JList` most of all time is spent on reading `HasIcon` resources (i.e. `ItmResource` and `SplResource`). It is strange that it occurs only at the first access to the list because I do not see that the readed resources were cached. Perhaps, it is a cache of the file system? In any case, in my experiments opening of STO files at the first access slows down slightly - to 0.5 seconds. Opening of item in sale lists by *View/Edit* button in STO for the first time takes ~2-3 seconds, subsequently opening do not differ on speed from the disabled icons. I.e. actually this line takes most of time:
https://github.com/Argent77/NearInfinity/blob/d022f5eee461b6925829727c6101009077349484/src/org/infinity/resource/IconCache.java#L51
when `object` is `ResourceRefEntry`. In that case at end method
https://github.com/Argent77/NearInfinity/blob/d022f5eee461b6925829727c6101009077349484/src/org/infinity/resource/key/ResourceEntry.java#L219-L230
is called, most time of this takes `ResourceFactory.getResource`.

For example, on following screenshot I comment out all code that creates images:
https://github.com/Argent77/NearInfinity/blob/d022f5eee461b6925829727c6101009077349484/src/org/infinity/resource/IconCache.java#L52-L60

Profile

I can try optimize this method by reading not whole resource, but just icon part of it, but possible this is not strongly will help. In anyway I will prefer do it in another PR. I think, that in current state performance is satisfactory. Besides, icons can be switched off, then no penalty to perfomance will exist

**Comment by Mingun** [comment]
Сlosed in preference to https://github.com/NearInfinityBrowser/NearInfinity/pull/112

**Pull request closed without merging**
