### PR TITLE
Synchronize tree structure when properties of the state/transition changed

### PR DESCRIPTION
**Pull request by Mingun**
This PR the first in the chain leading to implementation (almost) full-fledged editor of dialog from a tree. It solves the first problem -- synchronization of information in a tree with information in the flat entry list. It does not process adding and removals of entries -- for this purpose it is necessary to fix bug #100 first since because of it after the first removal the internal structure breaks and it is impossible to make with dialog anything else.

If you want to check that nothing is valid is forgotten, and all collections are cleaned from unnecessary nodes, I prepared a special branch with the debug code which I used for debugging -- https://github.com/Mingun/NearInfinity/tree/debug-synchronize-tree.

### CODE REVIEW

**Comment by Argent77** [comment]
I found one issue (possibly also related to #100) that throws an exception:
1. Open a DLG
2. Switch to Tree view and expand the first couple (or all) nodes
3. Switch back to Edit view
4. Select a State entry that has been loaded in the Tree view and edit "First response index".
```
java.lang.IndexOutOfBoundsException: toIndex = 2
	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1012)
	at java.util.ArrayList.subList(ArrayList.java:1004)
	at org.infinity.resource.dlg.DlgTreeModel.removeChildTransitions(DlgTreeModel.java:398)
	at org.infinity.resource.dlg.DlgTreeModel.changeStateFirstTrans(DlgTreeModel.java:316)
	at org.infinity.resource.dlg.DlgTreeModel.propertyChange(DlgTreeModel.java:176)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at org.infinity.resource.AbstractStruct.propertyChange(AbstractStruct.java:1226)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at org.infinity.resource.AbstractStruct.propertyChange(AbstractStruct.java:1226)
	at org.infinity.datatype.Datatype.firePropertyChange(Datatype.java:226)
	at org.infinity.datatype.DecNumber.setValue(DecNumber.java:144)
	at org.infinity.datatype.DecNumber.update(DecNumber.java:60)
	at org.infinity.resource.AbstractStruct.setValueAt(AbstractStruct.java:395)
	at javax.swing.JTable.setValueAt(JTable.java:2744)
	...
```

**Comment by Mingun** [comment]
Yes, initially I did not fix this error since it was hided by #100. But now it is fixed. Now dialog shows broken references in red color, as shown in a screenshot:
BrokenReferences

**Comment by Mingun** [comment]
@Argent77, can you look again at this please? I have some ideas for further improvements that based on this feature

**Comment by Mingun** [comment]
Сlosed in preference to https://github.com/NearInfinityBrowser/NearInfinity/pull/110

**Pull request closed without merging**
